### ISSUE TITLE
安装脚本自动版本获取不可用

### ISSUE THREAD

**Issue by dssgsra** [NapNeko/NapCat-Termux#1]
https://github.com/NapNeko/NapCat-Termux/blob/059441c9a15eca2cd5fec6f7f38a55017056a8fd/napcat.sh#L15

https://api.github.com/repos/NapNeko/NapCatQQ/releases/latest

{
    "message": "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}

**Comment by MliKiowa** [comment]
触发速率限制了
